data:
  name: McWilliams2D
  paths: ['McWilliams2d_128x128_N1000_Re5000_T30.pt']
  Re: 5000
  offset: 0
  total_num: 1000
  raw_res: [128, 128, 30]
  n_data_samples: 800
  data_res: [128, 128, 30]  # resolution in 1 second
  pde_res: [128, 128, 30]   # resolution in 1 second
  a_offset: 0
  n_a_samples: 200
  testoffset: 800
  n_test_samples: 200
  t_duration: 1.0
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  modes3: [12, 12, 12, 12]
  fc_dim: 128
  act: gelu
  pad_ratio: [0, 0.125]

train:
  batchsize: 4
  start_iter: 0
  num_iter: 50_001
  milestones: [20_000, 40_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_step: 5000
  eval_step: 5000

test:
  batchsize: 2
  data_res: [128, 128, 30]
  ckpt: model-400.pt

log:
  logdir: Re500-1_8s-800-FNO-s
  entity: hzzheng-pino
  project: PINO-KF-Re500
  group: Re500-1_8s-800-FNO-s